### ISSUE TITLE
New version with reveal 4

### ISSUE THREAD

**Issue by rstropek** [vivaxy/node-reveal#28]
Hi!

You are doing awesome work! You project makes working with revealjs so much more fun.

Can you already say when you will publish a new version on npm that includes revealjs 4? I saw you already reference v4 on GitHub. Does that mean that new release on npm is not that far away?

Greetings,
Rainer.

**Comment by vivaxy** [comment]
Upgraded. https://github.com/vivaxy/node-reveal/commit/a2231f5de49c6861d1a621254ddd91b762f48963

**Comment by rstropek** [comment]
Wow, that was fast. Thank you!
