### ISSUE TITLE
Update to reveal 3.9.2

### ISSUE THREAD

**Issue by chbndrhnns** [vivaxy/node-reveal#7]
Would you be able to bump the reveal version to 3.9.2?

**Comment by vivaxy** [comment]
What do you expect from reveal.js@3.9.2

**Comment by chbndrhnns** [comment]
Especially this feature: https://github.com/hakimel/reveal.js/blob/master/README.md#step-by-step-highlights

**Comment by vivaxy** [comment]
Resolved.
Commit: https://github.com/vivaxy/node-reveal/commit/dc68d0eeee39fdc484788ddc67a51066905bf798.
Version: [2.2.0](https://github.com/vivaxy/node-reveal/blob/master/CHANGELOG.md#220-2020-03-07)
